spring:
  application:
    name: api
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1500ms
      additional-paths: src/main/java, src/main/resources
    livereload:
      enabled: false
