spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3307/sitco_db?createDatabaseIfNotExist=true
    username: root
    password: D0ckerQLS1TCo@
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1500ms
      additional-paths: src/main/java, src/main/resources
    livereload:
      enabled: false
